name: Docker image

on:
  push:
    branches:
      - "main"
    tags:
      - "*"
  workflow_dispatch: {}

env:
  AR_REPO_LOCATION: "europe-west3-docker.pkg.dev"

jobs:
  build_and_push:
    if: ${{ github.actor != 'dependabot[bot]' }}
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"

    runs-on: ubuntu-latest

    name: Build server image
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: europe-west3-docker.pkg.dev/hyle-413414/hyle-docker/degen-party

      - name: Cache docker image
        id: cache
        uses: actions/cache@v4
        with:
          path: docker-image-cache.tar
          key: ${{ runner.os }}-docker-image

      - name: Load docker image
        if: steps.cache.outputs.cache-hit == 'true'
        run: docker load -i docker-image-cache.tar

      - name: Docker Auth
        id: docker-auth
        uses: "docker/login-action@v3"
        with:
          username: _json_key
          password: ${{ secrets.GOOGLE_CREDENTIALS }}
          registry: ${{ env.AR_REPO_LOCATION }}

      - name: Build and push builder image
        id: builder
        continue-on-error: true
        uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile.server
          context: .
          build-args: |
            DEP_IMAGE=europe-west3-docker.pkg.dev/hyle-413414/hyle-docker/degen-party-builder:latest
          target: builder
          tags: europe-west3-docker.pkg.dev/hyle-413414/hyle-docker/degen-party-builder:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push builder image (slow path)
        if: steps.builder.outcome == 'failure'
        uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile.server
          context: .
          target: builder
          tags: europe-west3-docker.pkg.dev/hyle-413414/hyle-docker/degen-party-builder:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Save docker image
        run: docker save europe-west3-docker.pkg.dev/hyle-413414/hyle-docker/degen-party-builder:latest -o docker-image-cache.tar

      - name: Build docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile.server
          context: .
          build-args: |
            DEP_IMAGE=europe-west3-docker.pkg.dev/hyle-413414/hyle-docker/degen-party-builder:latest
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build_ui_and_push:
    if: ${{ github.actor != 'dependabot[bot]' }}
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"

    runs-on: ubuntu-latest

    name: Build frontend image
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: europe-west3-docker.pkg.dev/hyle-413414/hyle-docker/degen-party-ui

      - name: Docker Auth
        id: docker-auth
        uses: "docker/login-action@v3"
        with:
          username: _json_key
          password: ${{ secrets.GOOGLE_CREDENTIALS }}
          registry: ${{ env.AR_REPO_LOCATION }}

      - name: Build docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile.ui
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
